# Generated by Django 2.2.6 on 2019-11-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('political_view', models.CharField(max_length=1, null=True)),
                ('correct_answers', models.IntegerField(default=0)),
                ('quiz_id', models.IntegerField()),
            ],
        ),
    ]
